# Generated by Django 4.2.9 on 2026-09-03 18:13

from django.db import migrations, models
import django.db.models.deletion
import payroll.models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_base_salary_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('pdf', models.FileField(upload_to=payroll.models.payslip_upload_path)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.employee')),
            ],
            options={
                'ordering': ['-period_year', '-period_month', 'employee__employee_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee', 'period_year', 'period_month'), name='unique_employee_payslip_period'),
        ),
    ]
